SWANLAB_PROJECT="qwen-medical-cpt" \
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 training/pretraining.py \
    --model_name_or_path /home/apulis-dev/userdata/2026/MedicalGPT/model/Qwen3.5-2B \
    --train_file_dir /home/apulis-dev/userdata/2026/MedicalGPT/data/medical/cpt \
    --validation_file_dir /home/apulis-dev/userdata/2026/MedicalGPT/data/medical/cpt \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --max_train_samples 50000 \
    --max_eval_samples 100 \
    --num_train_epochs 0.5 \
    --learning_rate 5e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --eval_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 13 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 10 \
    --block_size 512 \
    --packing True \
    --output_dir outputs-pt-qwen-v1 \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --bf16 \
    --report_to swanlab \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache
